
Vagrant.configure("2") do |config|
    config.vm.box_check_update = false

    config.vm.box = "peru/ubuntu-20.04-server-amd64"
    config.vm.hostname = "sparky"
    
  
    # Réseaux
    config.vm.network "private_network", ip: "192.168.100.10"
  
    # Fournisseur
    config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "1024"
      vb.cpus = 1
    end


    # Provision
    config.vm.provision "shell", path: "scripts/update.sh"
    config.vm.provision "shell", path: "scripts/install_nodejs.sh"
    config.vm.provision "shell", path: "scripts/install_git.sh"
    config.vm.provision "shell", path: "scripts/install_mongodb.sh"
    config.vm.provision "shell", path: "scripts/install_nginx.sh"
end